config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'resume', to: 'static_pages#resume'
  get 'projects', to: 'static_pages#projects'

  post 'contacts', to: 'contacts#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create
    ContactMailer.send_contact_email(mailer_params).deliver
    redirect_to(root_path, :notice => 'Your message has been sent')
  end

  private
    def mailer_params
      params.permit(:name, :email, :twitter, :message)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def resume
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title='')
    base = 'Landon Eric West'
    page_title.empty? ? base : "#{base} | #{page_title}"
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_contact_form.erb
<%= form_tag({controller: 'contacts', action: 'create'}, method: 'post', id: 'contact-form') do %>
  <h1>Get In Touch</h1>

  <p>I'm always looking for new opportunities to grow. I'd love to hear from you!</p>

  <div class="input-group">
    <%= label_tag :name, 'Name*' %>
    <%= text_field_tag :name, nil, class: 'contact-input', required: true %>
  </div>

  <div class="input-group">
    <%= label_tag :email, 'Email*' %>
    <%= email_field_tag :email, nil, class: 'contact-input', required: true %>
  </div>

  <div class="input-group">
    <%= label_tag :twitter, '@twitter?' %>
    <%= text_field_tag :twitter, nil, class: 'contact-input' %>
  </div>

  <div class="input-group">
    <%= label_tag :message, "What's on your mind?*" %>
    <%= text_area_tag :message, nil, class: 'contact-input', size: '12x4', required: true %>
  </div>

  <span>* indicates required field</span>

  <%= submit_tag 'Send it!', id: 'send-btn' %>
<% end %>

app/views/layouts/_main_footer.erb
<footer>
  <ul>
    <li>
      <a href="https://github.com/LandonWest" class="flex-icon" target="_blank">
        <i class="fa fa-github fa-2x" aria-hidden="true"></i>
        github
      </a>
    </li>
    <li>
      <a href="http://codepen.io/Lando726/" class="flex-icon" target="_blank">
        <i class="fa fa-codepen fa-2x" aria-hidden="true"></i>
        codepen
      </a>
    </li>
    <li>
      <a href="https://twitter.com/Lando726" class="flex-icon" target="_blank">
        <i class="fa fa-twitter fa-2x" aria-hidden="true"></i>
        twitter
      </a>
    </li>
    <li>
      <a href="https://www.instagram.com/landoutwest/" class="flex-icon" target="_blank">
        <i class="fa fa-instagram fa-2x" aria-hidden="true"></i>
        instagram
      </a>
    </li>
    <li>
      <a href="https://www.linkedin.com/in/landonwest/" class="flex-icon" target="_blank">
        <i class="fa fa-linkedin fa-2x" aria-hidden="true"></i>
        linkedin
      </a>
    </li>
  </ul>
</footer>

app/views/layouts/_topnav.html.erb
<nav id="topnav">
  <ul>
    <li><%= link_to 'Home', root_path, class: 'up' %></li>
    <li><%= link_to 'Projects', projects_path, class: 'up' %></li>
    <li><%= link_to 'Resume', resume_path, class: 'up' %></li>
    <li><%= link_to 'Contact', root_path(anchor: 'contact'), class: 'up' %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/3f708d5aa6.js"></script>
  </head>

  <body class="c-<%= controller_name %> a-<%= action_name %>" >
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <%= yield %>

    <script type="text/javascript">
      setTimeout(function() {
        $('.notice').fadeOut(3000);
      }, 2000);
    </script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-77564919-1', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="hero-banner js-scroll-target">
  <div class="hero-headline">
    <h1>Landon<br>
      Eric<br>
      West</h1>
    <h2>Full Stack Developer</br>
      With a Passion for</br>
      Art and Technology</h2>
  </div>
</div>

<%= render 'layouts/topnav' %>

<div class="page-wrap">
  <section id="about">
    <div class="col-2-flex hl-quote">
      <div class="profile-pic">
        <%= image_tag('landon_profile_wh') %>
      </div>

      <div class="quote-wrap">
        <blockquote>
          "Programming is a natural continuation of my life-long love for creating things"
        </blockquote>
      </div>
    </div>

    <div class="col-2-flex">
      <p class="flex-article md-line-space">Hi, I'm Landon West. I have a creative mind and a passion for web development, great design, and user experience. I'm a self-starter who takes pride in producing quality work. I'm hungry for knowledge and eager to advance my skills. I've found that programming is a natural continuation of my life-long love for creating things.</p>

      <p class="flex-article md-line-space">Keeping up on the latest web, mobile, and VR trends drives me. You can find me at one of many San Francisco tech meetups or follow me on Twitter where I post things I find exciting or helpful. Aside from technology, I love the outdoors and have been taking advantage of all the amazing places to hike and explore in the Bay Area. I also really enjoy shooting landscape and architecture photography.</p>
    </div>

    <div class="social-icons">
      <ul class="flex-list">
        <li>
          <a href="https://github.com/LandonWest" class="flex-icon" target="_blank">
            <i class="fa fa-github fa-4x" aria-hidden="true"></i>
            github
          </a>
        </li>
        <li>
          <a href="http://codepen.io/Lando726/" class="flex-icon" target="_blank">
            <i class="fa fa-codepen fa-4x" aria-hidden="true"></i>
            codepen
          </a>
        </li>
        <li>
          <a href="https://twitter.com/Lando726" class="flex-icon" target="_blank">
            <i class="fa fa-twitter fa-4x" aria-hidden="true"></i>
            twitter
          </a>
        </li>
        <li>
          <a href="https://www.instagram.com/landoutwest/" class="flex-icon" target="_blank">
            <i class="fa fa-instagram fa-4x" aria-hidden="true"></i>
            instagram
          </a>
        </li>
        <li>
          <a href="https://www.linkedin.com/in/landonwest/" class="flex-icon" target="_blank">
            <i class="fa fa-linkedin fa-4x" aria-hidden="true"></i>
            linkedin
          </a>
        </li>
      </ul>
    </div>
  </section>

  <section id="projects">
    <h2>Recent Projects</h2>

    <div class="proj-wrap">
      <div id="proj-prev-propeller" class="proj-prev overlay">
        <h2>
          <%= link_to 'Propeller Labs', projects_path(anchor: 'proj-propeller')%>
        </h2>
      </div>

      <div id="proj-prev-swanson" class="proj-prev overlay">
        <h2>
          <%= link_to projects_path(anchor: 'proj-swanson') do %>
          Ron Swanson<br>
          Quote Generator
          <% end %>
        </h2>
      </div>

      <div id="proj-prev-patchatech" class="proj-prev overlay">
        <h2>
          <%= link_to 'PatchaTech', projects_path(anchor: 'proj-patchatech') %>
        </h2>
      </div>
    </div>
  </section>

  <h2>Latest Tweets</h2>

  <div class="col-2-flex contwit">
    <section id="twitter-cont">
      <div class="twitter-ribbon">
        <a class="twitter-timeline"
          data-height="100%"
          data-width="100%"
          data-theme="light"
          data-tweet-limit="3"
          data-chrome="nofooter noborders"
          href="https://twitter.com/Lando726">
          Tweets by Lando726
        </a>

        <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>
    </section>

    <section id="contact">
      <%= render 'layouts/contact_form' %>
    </section>
  </div>
</div>

<%= render 'layouts/main_footer' %>

<script type="text/javascript">
  var target = $('.js-scroll-target');
  var nav = $('#topnav');

  $(window).on('scroll', function() {
    if ( window.scrollY >= target.outerHeight() ) {
      nav.addClass('nav-scrolled');
    } else {
      nav.removeClass('nav-scrolled');
    }
  });
</script>

app/views/static_pages/projects.html.erb
<%= render 'layouts/topnav' %>

<div class="page-wrap">

  <div class="page-header">
    <h1>PROJECTS</h1>

    <p class="md-line-space">
      Here are a few projects I'm proud of. Code is available on <a href="https://github.com/LandonWest" class="p-link-color" target="_blank">GitHub</a>.
      Please check out my <a href="http://codepen.io/Lando726/" class="p-link-color" target="_blank">CodePen</a> account for more of my front-end UI work.
    </p>
  </div>

  <div id="proj-propeller" class="proj-tile">
    <h2>Propeller Labs</h2>

    <div class="col-2-flex">
      <div class="flex-article">
        <p>I was contracted by Propeller Labs, a software development studio, to code their redesigned company website. I used Ruby on Rails and deployed to Heroku. The entire site was styled with custom CSS (SCSS) and jQuery for simple animations.</p>
        <p>Besides the complex, custom layout, some of the more challenging aspects of the project were connecting to different APIs including Meetup.com, Medium.com, and Instagram to retreive and display upcomming meetups, recent blog articles, and latest Instagram pictures.</p>
      </div>

      <div class="flex-article">
        <ul class="md-line-space">
          <li>Fully Responsive</li>
          <li>Ruby on Rails</li>
          <li>SCSS</li>
          <li>jQuery</li>
          <li>APIs</li>
          <li>GIT</li>
          <li>Heroku</li>
        </ul>
      </div>
    </div>

    <div class="pic-row">
      <div class="pic-cont">
        <div class="propeller-gif img-desktop"></div>
      </div>
      <div class="pic-cont">
        <%= image_tag('propeller_projects_dt.png') %>
      </div>
    </div>

    <div class="pic-row">
      <div class="pic-cont">
        <%= image_tag('propeller_medium_dt.png') %>
      </div>
      <div class="pic-cont">
        <%= image_tag('propeller_ig_dt.png') %>
      </div>
    </div>


    <div class="pic-row mb-pic-row">
      <div class="pic-cont">
        <%= image_tag('propeller_instant_mb.png') %>
      </div>
      <div class="pic-cont">
        <%= image_tag('propeller_menu_mb.png') %>
      </div>
      <div class="pic-cont">
        <%= image_tag('propeller_team_mb.png') %>
      </div>
    </div>
  </div>

  <div id="proj-swanson" class="proj-tile">
    <h2>Ron Swanson Quote Generator</h2>

    <a href="http://ronswansonquotes.xyz" class="p-link-color" target="_blank">
      RonSwansonQuotes.xyz</a>

    <div class="col-2-flex">
      <div class="flex-article">
        <p>I created this quote generator web app by pulling from an open source api that serves Ron Swanson quotes. I styled it to be responsive with an emphasis on mobile. It is deployed using GitHub pages. The coolest feature is it allows you to share your favorite quote on Facebook or Twitter!</p>
      </div>
    </div>

    <div class="pic-row mb-pic-row">
      <div class="pic-cont">
        <%= image_tag('swanson_1_mb.png') %>
      </div>
      <div class="pic-cont">
        <%= image_tag('swanson_2_mb.png') %>
      </div>
      <div class="pic-cont">
        <%= image_tag('swanson_3_mb.png') %>
      </div>
    </div>
  </div>

  <div id="proj-weather" class="proj-tile">
    <h2>Weather App</h2>

      <a href="https://landonwest.github.io/weather-app"  class="p-link-color" target="_blank">
        landonwest.github.io/weather-app</a>
    </p>

    <div class="col-2-flex">
      <div class="flex-article">
        <p>I created this Current Weather web app by pulling a users location using browser geolocation, parsing their city and state, and pulling their current temperature and weather conditions from APIs. Temperature can be displayed in Farenheit or Celcius.</p>
      </div>
    </div>

    <div class="pic-row mb-pic-row">
      <div class="pic-cont">
        <%= image_tag('weather_2_mb.png') %>
      </div>
      <div class="pic-cont">
        <%= image_tag('weather_1_mb.png') %>
      </div>
      <div class="pic-cont">
        <%= image_tag('weather_3_mb.jpg') %>
      </div>
    </div>
  </div>

  <div id="proj-patchatech" class="proj-tile">
    <h2>PatchaTech</h2>

    <a href="http://www.patchatech.com/" class="p-link-color">PatchaTech.com</a>

    <div class="col-2-flex">
      <div class="flex-article">
        <p>This is my capstone project at DevPoint Labs, a full-time, 11-week, immersive, web development program. I collaborated on all aspects of the project on a team of three people.</p>

        <p>
          The site lets you sign up for a free account, search for, view, and rate tutorial videos. You can also upload your own video tutorials.
          <span class="disclaimer">*This project is no longer actively maintained</span>
        </p>
      </div>

      <div class="flex-article">
        <ul class="md-line-space">
          <li>Ruby on Rails</li>
          <li>PostgreSQL</li>
          <li>Image/Video uploads with CarierWave</li>
          <li>AWS S3</li>
          <li>HTML5 Video</li>
          <li>ElasticSearch</li>
          <li>User Authentication</li>
          <li>Foundation responsive front-end framework</li>
          <li>Heroku</li>
          <li>Git</li>
        </ul>
      </div>
    </div>


    <div class="pic-row">
      <div class="pic-cont">
        <%= image_tag('patchatech_home_dt.png') %>
      </div>
      <div class="pic-cont">
        <%= image_tag('patchatech_tutorials_dt.png') %>
      </div>
    </div>

    <div class="pic-row">
      <div class="pic-cont">
        <%= image_tag('patchatech_profile_dt.png') %>
      </div>
      <div class="pic-cont">
        <%= image_tag('patchatech_tutorial_create_dt.png') %>
      </div>
    </div>
  </div>
</div>

<%= render 'layouts/main_footer' %>

app/views/static_pages/resume.html.erb
<%= provide :title, 'Resume' %>

<%= render 'layouts/topnav' %>

<div class="resume">
  <header>
    <h1>
      Landon<br>
      Eric<br>
      West
    </h1>

    <ul class="link-list res-links">
      <li>
        <a href="https://github.com/LandonWest" target="_blank">GitHub.com/LandonWest</a>
      </li>
      <li>
        <a href="https://codepen.io/Lando726" target="_blank">CodePen.io/Lando726</a>
      </li>
      <li>
        <a href="https://twitter.com/Lando726" target="_blank">Twitter.com/Lando726</a>
      </li>
      <li><a href="https://www.linkedin.com/in/landonwest">LinkedIn.com/in/LandonWest</a></li>
    </ul>

    <ul class="link-list res-links">
      <li><%= link_to 'LandonEricWest.com', root_path %></li>
      <li>
        <a href="mailto:landonwest5@gmail.com">LandonWest5 [at] gmail.com</a>
      </li>
      <li>
        <a href="https://goo.gl/maps/Qxosbo5NMAn" target="_blank">
          San Francisco, California
        </a>
      </li>
    </ul>
  </header>

  <section class="statement">
    <h2>Personal Statement</h2>

    <p class="italic">
      A creative mind with a passion for web development, great design, and user experience. A self-starter who takes pride in producing quality work, hungry for knowledge and eager to advance his skills.
    </p>
  </section>

  <section class="skills">
    <h2>Web Development Training &amp; Skills</h2>

    <h3>
      DevPoint Labs, 2014<br>
      11-week, immersive, full-stack web development program
    </h3>

    <ul>
      <li>Front End / Client Side technologies including HTML, CSS, JavaScript, jQuery, React, SASS / SCSS, AJAX, Responsive Design</li>
      <li>Server Side and Database technologies including Ruby, Rails, SQL, PostgreSQL, Bash</li>
      <li>Version control and collaboration via GIT and GitHub</li>
      <li>Software QA and testing with RSpec, MiniTest, Selenium</li>
      <li>Keeping up to date with current and emerging web technologies through relevant blogs, online training, meetups, and events</li>
    </ul>
  </section>

  <section class="work-exp">
    <h2>Work Experience</h2>

    <h3>
      Propeller Labs<span>Sept. 2016 - Current</span><br>
      Software Development Contractor
    </h3>
    <p class="italic">Followed Urbio VP of Operations, post sale, to a new venture at a fast-growing software development company</p>

    <ul>
      <li>Developing the company's new website according to specs of designer and growth team</li>
      <li>Writing a Ruby command line program to automate the process of gathering and processing industry-specific company and contact data</li>
      <li>Generating market and prospective business research for new web and mobile development</li>
    </ul>

    <h3>
      Urbio, Inc. <span>2014 - 2016</span><br>
      Operations &amp; Technology Coordinator
    </h3>
    <p class="italic">Started as an intern and was promoted to Associate of Urbio</p>

    <h4>Website development, helpdesk support</h4>
    <ul>
      <li>Web content management</li>
      <li>Added new products online, created sale banners</li>
      <li>Coordinated with outsourced web development firm on website redesign, making sure specs were built according to our requiremnts and quality testing the site before launch</li>
      <li>Coordinated with 3PL (third-party logistics warehouse), Ecommerce platform, and engineer to set up integration of XML feed for order and inventory flow. Alerted engineer of issues with transmission and manually re-sent data when necessary</li>
      <li>Took charge of project to find an internet company and get all wireless network equipment set up</li>
      <li>Partnered with IT professional to trace internet line through multi-story building and troubleshoot connection on the basement switchboard</li>
      <li>Trained employees on setup and use of new team messaging software</li>
      <li>Troubleshot and upgraded pc hardware</li>
      <li>Installed and set up VMs on Mac computers to run legacy Windows software in order to access retailer portals</li>
    </ul>

    <h4>Operations/Logistics</h4>
    <ul>
      <li>New product line launched in major retailers</li>
      <li>Coordinated logistics for both international and domestic shipments</li>
      <li>Created, organized and maintained a process for tracking shipments</li>
      <li>Set up procurement procedures</li>
      <li>Established relationships - set up/strengthened relationships with retail and logistics partners including OfficeMax/Depot, Target, Staples, and Saddle Creek Logistics</li>
      <li>Existing product testing/market research for new products</li>
      <li>Led and project-managed major transition to new 3PL</li>
      <li>Worked on a team to troubleshoot port strike issues, my role was to gather relevant information on container contents and due dates in order to influence decision process</li>
      <li>Kept detailed records and digital copies of all purchase orders, invoices, and bill of ladings</li>
      <li>Responsible for customer service emails, resolving issues etc.</li>
    </ul>

    <h3>Temporary Positions<span>2012 - 2014</span></h3>
    <p class="italic">I held a number of positions in the Los Angeles area while my wife finished a graduate degree program</p>
    <ul>
      <li>Security Officer (Hollywood Presbitarian Medical Center)</li>
      <li>Event Staff and Security (Contemporary Services Corporation)</li>
      <li>Various administrative positions</li>
    </ul>
  </section>

  <section class="edu">
    <h2>Education</h2>
    <h3>
      University of Utah, Bachelor of Arts, Middle East Studies: Persian, 2011
    </h3>
  </section>

  <section class="interests">
    <h3>Other Skills &amp; Interests</h3>
    <p>Hiking, photography, music, college football, basketball</p>
  </section>
</div>

<%= render 'layouts/main_footer' %>